In [2]:
import pickle, os
import numpy as np

from sklearn import datasets
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import roc_curve, auc, confusion_matrix, classification_report

from keras.models import Sequential, Model
from keras.layers import Input, Dense, Conv2D, Activation, MaxPool2D, Dropout, Flatten, BatchNormalization

Using TensorFlow backend.


In [60]:
# Pre-processing embeddings
EMBEDDING_DIR = "data/embedding/gae/"
embedding_files = os.listdir(EMBEDDING_DIR)
embedding_files.sort()

In [61]:
num_files = len(embedding_files)
print(num_files)
NUM_PATHWAY = 93
for i in range(286):
    print(embedding_files[i*NUM_PATHWAY])

26598
0_1-hsa00140.npy
0_10-hsa00140.npy
0_100-hsa00140.npy
0_101-hsa00140.npy
0_102-hsa00140.npy
0_103-hsa00140.npy
0_104-hsa00140.npy
0_105-hsa00140.npy
0_106-hsa00140.npy
0_107-hsa00140.npy
0_108-hsa00140.npy
0_109-hsa00140.npy
0_11-hsa00140.npy
0_110-hsa00140.npy
0_111-hsa00140.npy
0_112-hsa00140.npy
0_113-hsa00140.npy
0_114-hsa00140.npy
0_115-hsa00140.npy
0_116-hsa00140.npy
0_117-hsa00140.npy
0_118-hsa00140.npy
0_119-hsa00140.npy
0_12-hsa00140.npy
0_120-hsa00140.npy
0_121-hsa00140.npy
0_122-hsa00140.npy
0_123-hsa00140.npy
0_124-hsa00140.npy
0_125-hsa00140.npy
0_126-hsa00140.npy
0_127-hsa00140.npy
0_128-hsa00140.npy
0_129-hsa00140.npy
0_13-hsa00140.npy
0_130-hsa00140.npy
0_131-hsa00140.npy
0_132-hsa00140.npy
0_133-hsa00140.npy
0_134-hsa00140.npy
0_135-hsa00140.npy
0_136-hsa00140.npy
0_137-hsa00140.npy
0_138-hsa00140.npy
0_139-hsa00140.npy
0_14-hsa00140.npy
0_140-hsa00140.npy
0_141-hsa00140.npy
0_142-hsa00140.npy
0_143-hsa00140.npy
0_144-hsa00140.npy
0_145-hsa00140.npy
0_146-hsa0014

In [62]:
# file = "0_1-hsa00010.npy"
# id_pathway = np.load(os.path.join(EMBEDDING_DIR, file))
# print(id_pathway.shape)
# np.sum(id_pathway, axis=0)[np.newaxis,:].shape

# Sum of pathways
sum_data = [np.sum(np.load(os.path.join(EMBEDDING_DIR, file)), axis=0)[np.newaxis,:] for file in embedding_files]

# Flattened data
# flattened_data = [np.load(os.path.join(EMBEDDING_DIR, file)).reshape(1,-1) for file in embedding_files]

In [77]:
# Original matrix
matrix_data = [np.load(os.path.join(EMBEDDING_DIR, file)) for file in embedding_files]

In [81]:
print(matrix_data[1].shape)
print(len(embedding_files))
print(NUM_PATHWAY)

(63, 16)
26598
93


In [65]:
# Horizontally stack data to form one row per sample
data_list = []
for indv in range(286):
    start_index = indv * NUM_PATHWAY
    end_index = (indv + 1) * NUM_PATHWAY
    print(start_index, end_index)
    # Change from flattened_data
    data_list.append(np.hstack(sum_data[start_index:end_index]))
print(len(data_list))

0 93
93 186
186 279
279 372
372 465
465 558
558 651
651 744
744 837
837 930
930 1023
1023 1116
1116 1209
1209 1302
1302 1395
1395 1488
1488 1581
1581 1674
1674 1767
1767 1860
1860 1953
1953 2046
2046 2139
2139 2232
2232 2325
2325 2418
2418 2511
2511 2604
2604 2697
2697 2790
2790 2883
2883 2976
2976 3069
3069 3162
3162 3255
3255 3348
3348 3441
3441 3534
3534 3627
3627 3720
3720 3813
3813 3906
3906 3999
3999 4092
4092 4185
4185 4278
4278 4371
4371 4464
4464 4557
4557 4650
4650 4743
4743 4836
4836 4929
4929 5022
5022 5115
5115 5208
5208 5301
5301 5394
5394 5487
5487 5580
5580 5673
5673 5766
5766 5859
5859 5952
5952 6045
6045 6138
6138 6231
6231 6324
6324 6417
6417 6510
6510 6603
6603 6696
6696 6789
6789 6882
6882 6975
6975 7068
7068 7161
7161 7254
7254 7347
7347 7440
7440 7533
7533 7626
7626 7719
7719 7812
7812 7905
7905 7998
7998 8091
8091 8184
8184 8277
8277 8370
8370 8463
8463 8556
8556 8649
8649 8742
8742 8835
8835 8928
8928 9021
9021 9114
9114 9207
9207 9300
9300 9393
9393 9486
9486 

In [87]:
# Form image
data_list = []
for indv in range(286):
    start_index = indv * NUM_PATHWAY
    end_index = (indv + 1) * NUM_PATHWAY
    print(start_index, end_index)
    # Vertically stack data
    data_list.append(np.vstack(matrix_data[start_index:end_index]))

0 93
93 186
186 279
279 372
372 465
465 558
558 651
651 744
744 837
837 930
930 1023
1023 1116
1116 1209
1209 1302
1302 1395
1395 1488
1488 1581
1581 1674
1674 1767
1767 1860
1860 1953
1953 2046
2046 2139
2139 2232
2232 2325
2325 2418
2418 2511
2511 2604
2604 2697
2697 2790
2790 2883
2883 2976
2976 3069
3069 3162
3162 3255
3255 3348
3348 3441
3441 3534
3534 3627
3627 3720
3720 3813
3813 3906
3906 3999
3999 4092
4092 4185
4185 4278
4278 4371
4371 4464
4464 4557
4557 4650
4650 4743
4743 4836
4836 4929
4929 5022
5022 5115
5115 5208
5208 5301
5301 5394
5394 5487
5487 5580
5580 5673
5673 5766
5766 5859
5859 5952
5952 6045
6045 6138
6138 6231
6231 6324
6324 6417
6417 6510
6510 6603
6603 6696
6696 6789
6789 6882
6882 6975
6975 7068
7068 7161
7161 7254
7254 7347
7347 7440
7440 7533
7533 7626
7626 7719
7719 7812
7812 7905
7905 7998
7998 8091
8091 8184
8184 8277
8277 8370
8370 8463
8463 8556
8556 8649
8649 8742
8742 8835
8835 8928
8928 9021
9021 9114
9114 9207
9207 9300
9300 9393
9393 9486
9486 

In [92]:
# Save image
X_img_full = np.array(data_list)[:,:,:,np.newaxis]
# (n_samples, rows, cols, channels)
print(X_img_full.shape)
output_fpath = "data/embedding/X_img_full_93.npy"
np.save(output_fpath, X_img_full)

(286, 5179, 16, 1)


In [ ]:
# Save sum
X_sum_93 = np.vstack(data_list)
print(X_sum_93.shape)
# Save processed embedding data (286x104800)
# Save X_sum_158.npy (286, 2528)
# X_sum_93.npy (286, 1488)
output_fpath = "data/embedding/X_sum_93.npy"
np.save(output_fpath, X_sum_93)

In [89]:
print(data_list[0].shape)

(5179, 16)


In [7]:
# LOAD_DATA = "data/embedding/X_img_full_93.npy"
LOAD_DATA = "data/embedding/X_img_sum_93.npy"
# LOAD_DATA = "data/embedding/X_img_sum_158.npy"
# LOAD_DATA = "data/embedding/X_embedding.npy"
# Embeddings
X = np.load(LOAD_DATA)
print(X.shape)

# Datasets
# X_sum_158 = np.copy(X)
# print(X_sum_158.shape)
# print(X_sum_93.shape)

# Labels y
y = np.concatenate((np.repeat(0, 179), np.repeat(1, 107))).astype("int16")

# Random stratified split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    random_state=1,
                                                    test_size=0.25)

print(X_train.shape)

(286, 93, 16, 1)
(214, 93, 16, 1)


In [3]:
def create_mlp(dim):
    vector_input = Input(shape=dim)
    h = Dense(5000)(vector_input)
    h = Dropout(0.4)(h)
    h = Activation('relu')(h)
    h = Dense(2000)(h)
    h = Activation('relu')(h)
    h = Dense(1000)(h)
    h = Activation('relu')(h)
    h = Dense(500)(h)
    h = Activation('relu')(h)
    h = Dense(200)(h)
    h = Activation('relu')(h)
    h = Dense(100)(h)
    h = Activation('relu')(h)
    h = Dense(50)(h)
    h = Activation('relu')(h)
    h = Dense(20)(h)
    h = Activation('relu')(h)
    h = Dense(10)(h)
    h = Activation('relu')(h)
    h = Dense(8)(h)
    h = Activation('relu')(h)
    h = Dense(8)(h)
    h = BatchNormalization()(h)
    h = Activation('relu')(h)
    h = Dense(1)(h)
    h = BatchNormalization()(h)
    output = Activation('sigmoid')(h)
    model = Model(inputs=vector_input, outputs=output)
    
    return model

In [ ]:
batch_size = 10
n_epoch = 30

input_dim = (X_train.shape[1],)
mlp = create_mlp(dim=input_dim)
print(mlp.summary())

mlp.compile(loss='binary_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])

# 学習を開始します。
print('Training model...')
mlp_hist = mlp.fit(X_train, y_train,
                   epochs=n_epoch,
                   verbose=1,
                   validation_data=(X_test, y_test),
                   batch_size=batch_size)

# with open('../fig/mlp_history.pkl', 'wb') as file:
#     pickle.dump(mlp_hist.history, file)

# ## 学習結果の確認
print('MLP Validation Loss:', mlp_hist.history['loss'][-1])
print('MLP Validation Accuracy:', mlp_hist.history['acc'][-1])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 104800)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 5000)              524005000 
_________________________________________________________________
dropout_1 (Dropout)          (None, 5000)              0         
_________________________________________________________________
activation_1 (Activation)    (None, 5000)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 2000)              10002000  
_________________________________________________________________
activation_2 (Activation)    (None, 2000)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 1000)              2001000   
__________

In [ ]:
print(X_train.shape[1])

In [4]:
def create_cnn(dim=(5179,16,1)):
    model = Sequential()
    
    model.add(Conv2D(8, input_shape=dim,
                     kernel_size=(7, 3),
                     strides=(1, 1),
                     padding='same'))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))
    
    model.add(Conv2D(8,
                     kernel_size=(7, 3),
                     strides=(1, 1),
                     padding='same'))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))
   
    model.add(Flatten())
    model.add(Dense(64))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))
    model.add(Dense(64))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))
    model.add(Dense(1))
    model.add(Activation('sigmoid'))
    
    return model

In [8]:
batch_size = 10
n_epoch = 30

img_dim = X_train.shape
cnn = create_cnn(dim=img_dim[1:4])
print(cnn.summary())

cnn.compile(loss='binary_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])

# 学習を開始します。
print('Training model...')
cnn_hist = cnn.fit(X_train, y_train,
                   epochs=n_epoch,
                   verbose=1,
                   validation_data=(X_test, y_test),
                   batch_size=batch_size)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 93, 16, 8)         176       
_________________________________________________________________
activation_6 (Activation)    (None, 93, 16, 8)         0         
_________________________________________________________________
batch_normalization_5 (Batch (None, 93, 16, 8)         32        
_________________________________________________________________
dropout_5 (Dropout)          (None, 93, 16, 8)         0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 93, 16, 8)         1352      
_________________________________________________________________
activation_7 (Activation)    (None, 93, 16, 8)         0         
_________________________________________________________________
batch_normalization_6 (Batch (None, 93, 16, 8)         32        
__________

In [9]:
with open('dump/cnn_history-graph.pkl', 'wb') as file:
    pickle.dump(cnn_hist.history, file)

## 学習結果の確認
print('CNN Loss:', cnn_hist.history["val_loss"][-1])
print('CNN Accuracy:', cnn_hist.history["val_acc"][-1])

# Keras: Evaluation
y_proba = cnn.predict(X_test, batch_size)
y_predicted = np.array([1 if y >= 0.5 else 0 for y in y_proba])[:,np.newaxis]

print(classification_report(y_test, y_predicted))
print(confusion_matrix(y_test, y_predicted))

CNN Loss: 0.8309401240613725
CNN Accuracy: 0.513888900478681
              precision    recall  f1-score   support

           0       0.58      0.77      0.66        44
           1       0.23      0.11      0.15        28

   micro avg       0.51      0.51      0.51        72
   macro avg       0.40      0.44      0.40        72
weighted avg       0.44      0.51      0.46        72

[[34 10]
 [25  3]]


In [126]:
# Dump performance metrics
with open('dump/logreg_linear_smallmlp.pkl', 'wb') as file:
    pickle.dump(performance, file)

In [101]:
acc, y_prob, y_predicted, y_test = performance
print(acc)

for y_i in y_predicted:
    print(classification_report(y_test, y_i))
    print(confusion_matrix(y_test, y_i))

[0.3333333333333333, 0.4444444444444444, 0.5833333333333334, 0.6388888888888888, 0.4861111111111111]
              precision    recall  f1-score   support

           0       0.42      0.23      0.29        44
           1       0.29      0.50      0.37        28

   micro avg       0.33      0.33      0.33        72
   macro avg       0.35      0.36      0.33        72
weighted avg       0.37      0.33      0.32        72

[[10 34]
 [14 14]]
              precision    recall  f1-score   support

           0       0.55      0.50      0.52        44
           1       0.31      0.36      0.33        28

   micro avg       0.44      0.44      0.44        72
   macro avg       0.43      0.43      0.43        72
weighted avg       0.46      0.44      0.45        72

[[22 22]
 [18 10]]
              precision    recall  f1-score   support

           0       0.60      0.95      0.74        44
           1       0.00      0.00      0.00        28

   micro avg       0.58      0.58      0.58

In [98]:
# PCA
EMBEDDING_FILE = "data/embedding/X_embedding.npy"
X = np.load(EMBEDDING_FILE)
print(X.shape)
X_reduced = PCA(n_components=250).fit_transform(X)

# Save top 1000 principal components
output_fpath = "data/embedding/X_reduced.npy"
np.save(output_fpath, X_reduced)
print(X_reduced.shape)

(286, 104800)
(286, 250)


In [43]:
a = np.arange(12).reshape(4,3)
ls = [a,a,a,a,a,a]
np.array(ls)[:,:,:,np.newaxis].shape

(6, 4, 3, 1)